### ISSUE TITLE
Set up API calls, buy/sell functions 

### ISSUE THREAD

**Issue by FrancisMasangcay** [acm-projects/Fortunate#12]
Function should support taking in a stock symbol and order type, making API call for said symbol and then executing the order.

Make sure to only allow order executions on **valid** market days and times. (Weekdays 9am - 4pm EST) double check me on this.

**Comment by caleb-chou** [comment]
0bf0743 - Most of this is done, other than verifying time day and implementing the price fetching function. Will also work on implementing something to help with #15 soon.

**Comment by caleb-chou** [comment]
0fa9e3e - Trade function should be done.
